[package]
name = "graphforge-render"
version.workspace = true
edition.workspace = true

[dependencies]
graphforge-core = { path = "../graphforge-core" }
toml = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
serde_yml = { workspace = true }
